schema_version = "1.0.0"

id = "Annotation_Helper"
version = "3.0.9"
name = "Geometry Annotation Provider"
tagline = "Renders dense scenes and automatically provides annotation for each element of the scene."
maintainer = "Danylo Hrechyshkin"
type = "add-on"
tags = ["Render"]
blender_version_min = "4.2.0"
# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
license = ["SPDX:GPL-2.0-or-later"]